name: widgets
description: "A new Flutter package project."
version: 0.0.1
homepage: null
publish_to: none

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  google_mobile_ads: ^3.1.0

  gen:
    path: ../gen

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter




flutter: null
