/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package wedding_shopping_check

import org.gradle.testfixtures.ProjectBuilder
import org.gradle.api.Project
import spock.lang.Specification

/**
 * A simple unit test for the 'wedding_shopping_check.greeting' plugin.
 */
class Wedding_shopping_checkPluginTest extends Specification {
    def "plugin registers task"() {
        given:
        def project = ProjectBuilder.builder().build()

        when:
        project.plugins.apply("wedding_shopping_check.greeting")

        then:
        project.tasks.findByName("greeting") != null
    }
}
