/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package wedding_shopping_check

import org.gradle.api.Project
import org.gradle.api.Plugin

/**
 * A simple 'hello world' plugin.
 */
class Wedding_shopping_checkPlugin implements Plugin<Project> {
    void apply(Project project) {
        // Register a task
        project.tasks.register("greeting") {
            doLast {
                println("Hello from plugin 'wedding_shopping_check.greeting'")
            }
        }
    }
}
